// Code generated by oto; DO NOT EDIT.

package main

import (
	"context"
)

// Event is an instance like GopherCon 2020
type EventStore interface {
	CreateEvent(context.Context, Event) Event
	RetrieveEvent(context.Context, Event) Event
	UpdateEvent(context.Context, Event) Event
	DeleteEvent(context.Context, Event) error
}

// Conference is a brand like GopherCon
type ConferenceStore interface {
	CreateConference(context.Context, Conference) Conference
	RetrieveConference(context.Context, Conference) Conference
	UpdateConference(context.Context, Conference) Conference
	DeleteConference(context.Context, Conference) error
}

// GetConferenceRequest is the request object for ConferenceService.Get.
type GetConferenceRequestStore interface {
	CreateGetConferenceRequest(context.Context, GetConferenceRequest) GetConferenceRequest
	RetrieveGetConferenceRequest(context.Context, GetConferenceRequest) GetConferenceRequest
	UpdateGetConferenceRequest(context.Context, GetConferenceRequest) GetConferenceRequest
	DeleteGetConferenceRequest(context.Context, GetConferenceRequest) error
}

// GetConferenceResponse is the response object containing a single Conference
type GetConferenceResponseStore interface {
	CreateGetConferenceResponse(context.Context, GetConferenceResponse) GetConferenceResponse
	RetrieveGetConferenceResponse(context.Context, GetConferenceResponse) GetConferenceResponse
	UpdateGetConferenceResponse(context.Context, GetConferenceResponse) GetConferenceResponse
	DeleteGetConferenceResponse(context.Context, GetConferenceResponse) error
}

// ListConferenceRequest is the request object for ConferenceService.List.
type ListConferenceRequestStore interface {
	CreateListConferenceRequest(context.Context, ListConferenceRequest) ListConferenceRequest
	RetrieveListConferenceRequest(context.Context, ListConferenceRequest) ListConferenceRequest
	UpdateListConferenceRequest(context.Context, ListConferenceRequest) ListConferenceRequest
	DeleteListConferenceRequest(context.Context, ListConferenceRequest) error
}

// ListConferenceResponse is the response object containing a list of Conferences
type ListConferenceResponseStore interface {
	CreateListConferenceResponse(context.Context, ListConferenceResponse) ListConferenceResponse
	RetrieveListConferenceResponse(context.Context, ListConferenceResponse) ListConferenceResponse
	UpdateListConferenceResponse(context.Context, ListConferenceResponse) ListConferenceResponse
	DeleteListConferenceResponse(context.Context, ListConferenceResponse) error
}
